name: Deploy Le Rocher

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Bun
        uses: oven-sh/setup-bun@v2

      - name: Installer les dépendances
        run: bun install

      - name: Construire le site
        run: bun run build

      - name: Préparer le fallback SPA
        run: |
          cp ./dist/client/index.html ./dist/client/404.html
          touch ./dist/client/.nojekyll

      - name: Configurer GitHub Pages
        uses: actions/configure-pages@v5

      - name: Préparer le site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/client

      - name: Publier le site
        uses: actions/deploy-pages@v4
